version: '3.8'

services:

  celery-app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - 8023:8000
    env_file:
      - ./app/.env
    depends_on:
      - celery-app-db
      - rabbitmq

  celery-app-db:
    image: mysql:8.0.31
    restart: always
    env_file:
      - ./app/.env
    ports:
      - 3312:3306
    volumes:
      - celery-app-db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  celery-worker:
    build: ./app
    command: celery -A core worker --loglevel=INFO
    volumes:
      - ./app:/code
    depends_on:
      - celery-app
      - rabbitmq
    env_file:
      - ./app/.env
  
  celery-beat:
    build: ./app
    command: celery -A core beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./app:/code
    depends_on:
      - celery-app
      - rabbitmq
    env_file:
      - ./app/.env

volumes:
  celery-app-db:
